#!/usr/bin/env bash
set -euo pipefail

TEMPLATE=${1:-}
PORT=8050


usage() {
cat<<EOF

Perform envsubstitution on the given template then post it a locally running
server that assumes a VistA VM is also running.

${1:-}
EOF
exit 1
}

if [ -z "${TEMPLATE:-}" ]; then usage "template not specified"; fi
if [ ! -f "$TEMPLATE" ]; then usage "template not found: $TEMPLATE"; fi

shift

POST_ME=$(mktemp)
onExit() { rm $POST_ME; }
trap onExit EXIT


PROBLEMS=0
for templateVar in $(grep '\$.' $TEMPLATE | sed 's/.*\$\([A-Za-z0-9_]\+\).*/\1/')
do
  if [ -z "${!templateVar:-}" ]; then echo "Template variable not defined: $templateVar"; let PROBLEMS+=1; fi
done
if [ $PROBLEMS != 0 ]; then exit 1; fi

cat $TEMPLATE | envsubst > $POST_ME

LOG_REQUEST=${LOG_REQUEST:-false}
case ${LOG_REQUEST,,} in
  on|true|r*) cat $POST_ME |  jq . | sed -e 's/"\(access\|verify\)Code":.*/"\1Code": "REDACTED"/';;
  clear) jq . $POST_ME;;
esac

curl \
  -s \
  -XPOST \
  -H"Content-Type:application/json" \
  --data @$POST_ME \
  ${URL:-http://localhost:$PORT/v1/rpc} \
  $@
