#!/usr/bin/env bash



usage() {
cat<<EOF
$0 <build|run> [run-args]

Build or run the integration test docker image.

EOF
}

build() {
  mvn clean deploy \
    -DskipTests \
    -Dexec.skip=true \
    -Dsentinel.skipLaunch=true \
    -P'!standard' \
    -Prelease \
    -Ddocker.skip.push=true \
    -Dmaven.deploy.skip=true \
    -Ddocker.username=$DOCKER_USERNAME \
    -Ddocker.password="$DOCKER_PASSWORD"
}


run() {
  case $(uname) in
    Darwin) THIS_MACHINE="docker.for.mac.localhost";;
    Linux) THIS_MACHINE="localhost";;
    *) echo "Add support for your operating system: $(uname)"; exit 1;;
  esac
  docker run \
    --rm \
    --network="host" \
    -e DEPLOYMENT_ENVIRONMENT=${ENV:-local} \
    -e DEPLOYMENT_TEST_PROTOCOL=http \
    -e DEPLOYMENT_TEST_HOST=${THIS_MACHINE} \
    -e DEPLOYMENT_TEST_PORT=8050 \
    -e CLIENT_KEY="${CLIENT_KEY:-hello}" \
    -e VISTA_STANDARD_USER_ACCESS_CODE=${VISTA_ACCESS_CODE:-secret} \
    -e VISTA_STANDARD_USER_VERIFY_CODE=${VISTA_VERIFY_CODE:-secret} \
     vasdvp/lighthouse-charon-tests:latest $@
}

main() {
  local cmd=$1
  shift
  case "$cmd" in
    r|run) run $@;;
    b|build) build;;
    br) build && run $@;;
    *) usage "Unknown command $cmd"
  esac
}


main $@
