@startuml

|App|
start
:Search for coverage by patient;

|Vista-Fhir-Query|
:Convert request to RPC query;

|Charon API|
:Invoke RPC;

|VistA|
:Return RPC results;

|Charon API|
:Convert RPC results to invocation result;

|Vista-Fhir-Query|
:Translate results to Fhir response;
:Return response;

|App|
stop

@enduml
